# Welcome to Jekyll!
#

# Site settings
title: Demystify Camp 2018
description: |
  A camping festival to explore the art and craft of making things from scratch.<br />
  Near Bangalore. Nov 23 â€“ 25, 2018.
owner: Demystify # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://demystify.xyz" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
#  style: compressed
